const express=require('express'),axios=require('axios'),crypto=require('crypto'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),config=require('./config'),db=require('./lib/redis');
const app=express(),NONCES=new Map(),SESSIONS=new Map(),FAILED=new Map();
const MY_TRUSTED_URLS=['raw.githubusercontent.com/trianaq765-cmd','github.com/trianaq765-cmd','trianaq765-cmd','pastebin.com/u4kzwdEX','pastebin.com/raw/u4kzwdEX','u4kzwdEX','core%20lua.txt','key%202.txt','core lua.txt','key 2.txt'];
const BOT_UA_PATTERNS=['python','curl','wget','axios','node-fetch','aiohttp','httpx','requests/','postman','insomnia','discord','telegram','slack','scrapy','selenium','puppeteer','playwright','java/','okhttp','apache-http','libwww-perl','ruby','php/','go-http','got/','undici'];
const TRAP_HTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="refresh" content="0;url=https://www.google.com"><title>Redirecting...</title><style>*{margin:0;padding:0}body{background:#000;color:#fff;font-family:system-ui;display:flex;justify-content:center;align-items:center;height:100vh;flex-direction:column}.l{width:40px;height:40px;border:3px solid #333;border-top-color:#fff;border-radius:50%;animation:s 1s linear infinite;margin-bottom:20px}@keyframes s{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}</style><script>setTimeout(function(){location.href=["https://google.com","https://roblox.com"][Math.floor(Math.random()*2)]},1000)</script></head><body><div class="l"></div><p>Loading...</p></body></html>`;
function sha256(s){return crypto.createHash('sha256').update(s).digest('hex')}
function hmac(d,k){return crypto.createHmac('sha256',k).update(d).digest('hex')}
function secureCompare(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;try{return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))}catch{return false}}
function getIP(r){return(r.headers['x-forwarded-for']||'').split(',')[0].trim()||r.headers['x-real-ip']||r.ip||'0.0.0.0'}
function getHWID(r){return r.headers['x-hwid']||null}
function genNonce(){const n=crypto.randomBytes(24).toString('hex');NONCES.set(n,Date.now());return n}
function genSessionKey(u,h,t,s){return hmac(`${u}:${h}:${t}:${Math.floor(t/3600)}`,s).substring(0,32)}
function genFakeScript(){const r=l=>{let s='';const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_';for(let i=0;i<l;i++)s+=c[Math.floor(Math.random()*c.length)];return s};const v=Array.from({length:20},()=>r(Math.floor(Math.random()*6)+2));return`local ${v[0]}=(function()local ${v[1]}={};local ${v[2]}=0;for ${v[3]}=1,100 do ${v[2]}=${v[2]}+${v[3]} end;return ${v[2]} end)();`}
function isBrowser(r){if(r.headers['sec-fetch-dest'])return true;if(r.headers['sec-fetch-mode'])return true;if(r.headers['sec-fetch-site'])return true;if(r.headers['sec-ch-ua'])return true;if(r.headers['sec-ch-ua-mobile'])return true;if(r.headers['sec-ch-ua-platform'])return true;if(r.headers['upgrade-insecure-requests'])return true;const accept=r.headers['accept']||'';const hasLang=!!r.headers['accept-language'];const hasCookie=!!r.headers['cookie'];if(accept.includes('text/html')&&hasLang)return true;if(hasLang&&hasCookie)return true;return false}
function isBot(r){const ua=(r.headers['user-agent']||'').toLowerCase();if(!ua||ua.length<5)return true;if(BOT_UA_PATTERNS.some(p=>ua.includes(p)))return true;if(ua==='mozilla/5.0')return true;const hasOrigin=!!r.headers['origin'];const hasReferer=!!r.headers['referer'];if(hasOrigin&&!r.headers['origin'].includes('roblox'))return true;if(hasReferer)return true;return false}
function isValidRequest(r){if(isBrowser(r))return{valid:false,reason:'browser'};if(isBot(r))return{valid:false,reason:'bot'};return{valid:true,reason:'executor'}}
async function logAccess(r,a,s,d={}){const log={ip:getIP(r),hwid:getHWID(r),ua:(r.headers['user-agent']||'').substring(0,80),action:a,success:s,path:r.path,ts:new Date().toISOString(),...d};await db.addLog(log);return log}
function genChallenge(){const types=['math','bitwise','sequence','sum'];const type=types[Math.floor(Math.random()*types.length)];switch(type){case'math':const ops=['+','-','*'];const op=ops[Math.floor(Math.random()*ops.length)];const a=Math.floor(Math.random()*50)+10,b=Math.floor(Math.random()*20)+5,c=Math.floor(Math.random()*10)+1;let ans;switch(op){case'+':ans=(a+b)*c;break;case'-':ans=(a-b)*c;break;case'*':ans=(a*b)+c;break}return{type:'math',puzzle:{a,b,c,op},answer:ans};case'bitwise':const x=Math.floor(Math.random()*200)+50,y=Math.floor(Math.random()*100)+20;const bops=['xor','and','or'];const bop=bops[Math.floor(Math.random()*bops.length)];let bans;switch(bop){case'xor':bans=x^y;break;case'and':bans=x&y;break;case'or':bans=x|y;break}return{type:'bitwise',puzzle:{x,y,op:bop},answer:bans};case'sequence':const start=Math.floor(Math.random()*15)+1,step=Math.floor(Math.random()*8)+2;const seq=[start,start+step,start+step*2,start+step*3];return{type:'sequence',puzzle:{seq},answer:start+step*4};default:const nums=Array.from({length:5},()=>Math.floor(Math.random()*50)+1);return{type:'sum',puzzle:{numbers:nums},answer:nums.reduce((a,b)=>a+b,0)}}}
function isObfuscated(s){if(!s)return false;return[/IronBrew/i,/Prometheus/i,/Moonsec/i,/Luraph/i,/PSU/i,/Bytecode/i].some(r=>r.test(s.substring(0,500)))}
async function getScript(){const cached=await db.getCachedScript();if(cached)return cached;if(!config.SCRIPT_SOURCE_URL)return null;try{const res=await axios.get(config.SCRIPT_SOURCE_URL,{timeout:30000,headers:{'User-Agent':'Roblox/WinInet','Accept':'*/*'},maxContentLength:50000000});if(typeof res.data==='string'&&res.data.length>50){await db.setCachedScript(res.data);return res.data}}catch(e){}return null}
function wrapScript(script,serverUrl){const o=config.OWNER_USER_IDS.join(','),w=config.WHITELIST_USER_IDS.join(','),b=`${serverUrl}/api/ban`,hb=`${serverUrl}/api/heartbeat`;return`local _O={${o}} local _W={${w}} local _B="${b}" local _HB="${hb}" local _P=game:GetService("Players") local _L=_P.LocalPlayer local _S=game:GetService("StarterGui") local _C=game:GetService("CoreGui") local _H=game:GetService("HttpService") local _TS=game:GetService("TeleportService") local _A=true local _SD=false local _CON={} local _THR={} local _RDY=false local _SID="${crypto.randomBytes(16).toString('hex')}"
local _IT={g={},m={}}
local _PG=nil
pcall(function() _PG=_L:FindFirstChild("PlayerGui") or _L:WaitForChild("PlayerGui",3) end)
local function _isW(u) if not _W or #_W==0 then return false end for _,i in ipairs(_W) do if u==i then return true end end return false end
local function _isO(u) if not _O or #_O==0 then return false end for _,i in ipairs(_O) do if u==i then return true end end return false end
local function _n(t,x,d) pcall(function() _S:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3}) end) end
local function _hw() local s,r=pcall(function() if gethwid then return gethwid() end if get_hwid then return get_hwid() end return "FB_"..tostring(_L.UserId) end) return s and r or "UNK" end
local function _hp(u,d,m) local r=(syn and syn.request) or request or http_request or (http and http.request) if not r then return nil end m=m or"POST" local ok,res=pcall(function() return r({Url=u,Method=m,Headers={["Content-Type"]="application/json",["User-Agent"]="Roblox/WinInet",["x-hwid"]=_hw(),["x-roblox-id"]=tostring(_L.UserId),["x-place-id"]=tostring(game.PlaceId),["x-job-id"]=game.JobId,["x-session-id"]=_SID},Body=d and _H:JSONEncode(d) or nil}) end) if not ok then return nil end if res.StatusCode~=200 then return nil end local ps,pd=pcall(function() return _H:JSONDecode(res.Body) end) return ps and pd or nil end
local function _freeze() pcall(function() local sc=Instance.new("ScreenGui") sc.Name="X"..math.random(100000,999999) sc.IgnoreGuiInset=true sc.DisplayOrder=2147483647 sc.ResetOnSpawn=false sc.Parent=_C local fr=Instance.new("Frame") fr.Size=UDim2.new(1,0,1,0) fr.BackgroundColor3=Color3.new(0,0,0) fr.BorderSizePixel=0 fr.Parent=sc local tx=Instance.new("TextLabel") tx.Size=UDim2.new(1,0,1,0) tx.BackgroundTransparency=1 tx.Text="ACCESS DENIED" tx.TextColor3=Color3.new(1,0,0) tx.TextSize=48 tx.Font=Enum.Font.GothamBold tx.Parent=fr end) end
local function _fd(reason) _A=false _RDY=false _freeze() task.delay(0.5,function() pcall(function() _L:Kick(reason) end) task.wait(0.3) pcall(function() _TS:Teleport(9999999999) end) end) end
local function _ban(rs,t) if _SD then return end _SD=true _A=false _hp(_B,{hwid=_hw(),playerId=_L.UserId,playerName=_L.Name,reason=rs,toolsDetected=t or {},sessionId=_SID}) _n("⛔","Banned: "..rs,5) _fd(rs) end
local function _cl() if _SD then return end _SD=true _A=false _RDY=false for i=#_THR,1,-1 do pcall(task.cancel,_THR[i]) end for i=#_CON,1,-1 do pcall(function() _CON[i]:Disconnect() end) end _THR={} _CON={} end
_G._SCRIPT_CLEANUP=_cl
local _TP={"simplespy","httpspy","remotespy","hydroxide","infiniteyield","serverspy","scriptdumper","darkdex","dex_explorer"}
local _TM={"SimpleSpy","HttpSpy","RemoteSpy","Hydroxide","Dex","DexExplorer","InfiniteYield","IY_LOADED"}
local function _antiDebug() if not debug then return end if newcclosure then pcall(function() debug.getupvalue=newcclosure(function() return nil,nil end) debug.setupvalue=newcclosure(function() return nil end) debug.getlocal=newcclosure(function() return "x",nil end) debug.setlocal=newcclosure(function() return nil end) end) end end
local function _antiGC() if not getgc or not newcclosure then return end local _ogc=getgc local cc=0 getgc=newcclosure(function(i) cc=cc+1 if cc>20 then _ban("GC abuse",{"getgc"}) return {} end local ok,r=pcall(_ogc,i) if not ok then return {} end local c={} for _,v in pairs(r) do if type(v)~="function" then c[#c+1]=v end end return c end) end
local function _doSnap() local e=getgenv and getgenv() or _G for _,m in ipairs(_TM) do if rawget(e,m)~=nil then _IT.m[m]=true end end if _C then pcall(function() for _,g in pairs(_C:GetChildren()) do if g:IsA("ScreenGui") or g:IsA("Folder") then _IT.g[g.Name:lower()]=true end end end) end end
local function _snap() if _isW(_L.UserId) then _RDY=true return end _doSnap() task.wait(0.5) _doSnap() _RDY=true end
local function _chkNew(n,isM) if isM then return _IT.m[n]==nil else return _IT.g[n:lower()]==nil end end
local function _det() if not _RDY or not _A or _isW(_L.UserId) then return false end local e=getgenv and getgenv() or _G for _,m in ipairs(_TM) do if rawget(e,m)~=nil and _chkNew(m,true) then return true,"ENV",m end end if _C then for _,g in pairs(_C:GetChildren()) do if g:IsA("ScreenGui") then local nm=g.Name:lower() if _chkNew(nm,false) then for _,p in ipairs(_TP) do if nm:find(p,1,true) then return true,"GUI",g.Name end end end end end end return false end
local function _mon() if _isW(_L.UserId) then return end local th=task.spawn(function() while not _RDY do task.wait(0.3) end task.wait(3) while _A and not _SD do task.wait(15) local d,c,s=_det() if d then _ban("Tool: "..(s or c),{c,s}) break end end end) table.insert(_THR,th) end
local function _watchGui() if _isW(_L.UserId) then return end local function chk(gui) if not _A or _SD or not _RDY then return end if not gui:IsA("ScreenGui") then return end task.delay(1.5,function() if not _A or _SD then return end local nm=gui.Name:lower() if _chkNew(nm,false) then for _,p in ipairs(_TP) do if nm:find(p,1,true) then _ban("Tool: "..gui.Name,{"GUI",gui.Name}) return end end end end) end if _C then table.insert(_CON,_C.ChildAdded:Connect(chk)) end end
local function _heartbeat() local th=task.spawn(function() task.wait(10) while _A and not _SD do task.wait(25) local res=_hp(_HB,{sessionId=_SID,hwid=_hw(),timestamp=os.time()}) if res and res.action=="TERMINATE" then _ban("Session terminated",{}) break end end end) table.insert(_THR,th) end
local function _ownerOk() if not _O or #_O==0 then return true end for _,p in pairs(_P:GetPlayers()) do if _isO(p.UserId) and p~=_L then return false end end return true end
local function _ownerMon() if not _O or #_O==0 then return end local th=task.spawn(function() while _A and not _SD do task.wait(20) if not _ownerOk() then _n("⚠️","Owner detected",3) _cl() return end end end) table.insert(_THR,th) table.insert(_CON,_P.PlayerAdded:Connect(function(p) task.wait(1) if _isO(p.UserId) then _n("⚠️","Owner joined",3) _cl() end end)) end
if not _ownerOk() then _n("⚠️","Owner in server",3) return end
task.spawn(function() _antiDebug() _antiGC() _snap() _mon() _watchGui() _ownerMon() _heartbeat() end)
${script}`}
function getLoader(serverUrl){return`local S="${serverUrl}" local H=game:GetService("HttpService") local P=game:GetService("Players") local G=game:GetService("StarterGui") local L=P.LocalPlayer
local function n(t,x,d) pcall(function() G:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3}) end) end
local function hw() local s,r=pcall(function() if gethwid then return gethwid() end return "FB_"..tostring(L.UserId) end) return s and r or "UNK" end
local function ex() local s,r=pcall(function() if identifyexecutor then return identifyexecutor() end return "Unknown" end) return s and r or "Unknown" end
local function hp(u,d) local r=(syn and syn.request) or request or http_request or (http and http.request) if not r then return nil end local s,res=pcall(function() return r({Url=u,Method="POST",Headers={["Content-Type"]="application/json",["User-Agent"]="Roblox/WinInet",["x-hwid"]=hw(),["x-roblox-id"]=tostring(L.UserId),["x-place-id"]=tostring(game.PlaceId),["x-job-id"]=game.JobId},Body=H:JSONEncode(d)}) end) if not s or res.StatusCode~=200 then return nil end local ps,pd=pcall(function() return H:JSONDecode(res.Body) end) return ps and pd or nil end
local function xd(d,k) local r={} for i=1,#d do r[i]=string.char(bit32.bxor(d[i],string.byte(k,((i-1)%#k)+1))) end return table.concat(r) end
local function solve(p) if p.type=="math" then local a,b,c,op=p.puzzle.a,p.puzzle.b,p.puzzle.c,p.puzzle.op if op=="+" then return(a+b)*c elseif op=="-" then return(a-b)*c elseif op=="*" then return(a*b)+c end elseif p.type=="bitwise" then local x,y,op=p.puzzle.x,p.puzzle.y,p.puzzle.op if op=="xor" then return bit32.bxor(x,y) elseif op=="and" then return bit32.band(x,y) elseif op=="or" then return bit32.bor(x,y) end elseif p.type=="sequence" then local s=p.puzzle.seq return s[4]+(s[2]-s[1]) elseif p.numbers then local sum=0 for _,x in ipairs(p.numbers) do sum=sum+x end return sum end return 0 end
local function m() n("🔄","Connecting...",2) local c=hp(S.."/api/auth/challenge",{userId=L.UserId,hwid=hw(),placeId=game.PlaceId}) if not c or not c.success then n("❌",c and c.error or "Connection failed",5) if c and c.error and tostring(c.error):find("Banned") then task.wait(1) L:Kick("Banned") end return end local sol=solve(c) n("🔄","Verifying...",2) local v=hp(S.."/api/auth/verify",{challengeId=c.challengeId,solution=sol,timestamp=os.time()}) if not v or not v.success then n("❌",v and v.error or "Verification failed",5) return end n("✅","Loading...",2) local fs if v.mode=="raw" then fs=v.script else local p={} for i,ch in ipairs(v.chunks) do p[i]=xd(ch,v.key) end fs=table.concat(p) end local fn=loadstring(fs) if fn then fs=nil v=nil c=nil pcall(fn) end end
pcall(m)`}
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false,crossOriginResourcePolicy:false}));
app.use(cors({origin:'*',methods:['GET','POST','DELETE','OPTIONS'],allowedHeaders:['Content-Type','x-admin-key','x-hwid','x-roblox-id','x-place-id','x-job-id','x-session-id']}));
app.use(express.json({limit:'10mb'}));
app.set('trust proxy',1);
app.use(rateLimit({windowMs:60000,max:100,keyGenerator:r=>getIP(r)}));
app.use(async(req,res,next)=>{const ban=await db.isBanned(null,getIP(req),null);if(ban.blocked){return isBrowser(req)?res.status(403).type('html').send(TRAP_HTML):res.status(403).json({error:'Blocked'})}next()});
app.get('/',async(r,res)=>{const chk=isValidRequest(r);if(!chk.valid){await logAccess(r,chk.reason.toUpperCase()+'_ROOT',false);return chk.reason==='browser'?res.status(403).type('html').send(TRAP_HTML):res.type('text/plain').send(genFakeScript())}res.json({s:'ok',v:'6.2.0'})});
app.get('/health',(r,res)=>res.json({status:'ok'}));
app.get(['/loader','/api/loader.lua','/api/loader','/l'],async(r,res)=>{const chk=isValidRequest(r);if(!chk.valid){await logAccess(r,chk.reason.toUpperCase()+'_LOADER',false);return chk.reason==='browser'?res.status(403).type('html').send(TRAP_HTML):res.type('text/plain').send(genFakeScript())}await logAccess(r,'LOADER',true);const url=process.env.RENDER_EXTERNAL_URL||`${r.protocol}://${r.get('host')}`;res.type('text/plain').send(getLoader(url))});
app.post('/api/auth/challenge',async(r,res)=>{const chk=isValidRequest(r);if(!chk.valid){await logAccess(r,chk.reason.toUpperCase()+'_CHAL',false);return res.status(403).json({error:'Invalid client'})}const{userId,hwid,placeId}=r.body;if(!userId||!hwid||!placeId)return res.status(400).json({error:'Missing fields'});const uid=parseInt(userId),pid=parseInt(placeId);if(isNaN(uid)||isNaN(pid))return res.status(400).json({error:'Invalid'});const ip=getIP(r);const ban=await db.isBanned(hwid,ip,uid);if(ban.blocked)return res.status(403).json({success:false,error:'Banned: '+ban.reason});if(config.ALLOWED_PLACE_IDS.length>0&&!config.ALLOWED_PLACE_IDS.includes(pid))return res.status(403).json({error:'Game not allowed'});const id=crypto.randomBytes(16).toString('hex');const chal=genChallenge();await db.setChallenge(id,{id,userId:uid,hwid,placeId:pid,ip,...chal},60);await logAccess(r,'CHALLENGE',true,{userId:uid});res.json({success:true,challengeId:id,type:chal.type,puzzle:chal.puzzle,expiresIn:60})});
app.post('/api/auth/verify',async(r,res)=>{const chk=isValidRequest(r);if(!chk.valid){await logAccess(r,chk.reason.toUpperCase()+'_VER',false);return res.status(403).json({error:'Invalid client'})}const{challengeId,solution,timestamp}=r.body;if(!challengeId||solution===undefined||!timestamp)return res.status(400).json({error:'Missing fields'});const challenge=await db.getChallenge(challengeId);if(!challenge)return res.status(403).json({error:'Expired'});if(challenge.ip!==getIP(r))return res.status(403).json({error:'IP mismatch'});if(parseInt(solution)!==challenge.answer){await logAccess(r,'WRONG_SOL',false);return res.status(403).json({error:'Wrong solution'})}await db.deleteChallenge(challengeId);const script=await getScript();if(!script)return res.status(500).json({error:'Script not configured'});const url=process.env.RENDER_EXTERNAL_URL||`${r.protocol}://${r.get('host')}`;const wrapped=wrapScript(script,url);const isObf=config.SCRIPT_ALREADY_OBFUSCATED||isObfuscated(script);const sessionId=crypto.randomBytes(16).toString('hex');SESSIONS.set(sessionId,{hwid:challenge.hwid,ip:challenge.ip,created:Date.now()});if(isObf){await logAccess(r,'SCRIPT',true,{userId:challenge.userId});return res.json({success:true,mode:'raw',script:wrapped,sessionId,ownerIds:config.OWNER_USER_IDS,whitelistIds:config.WHITELIST_USER_IDS})}const key=genSessionKey(challenge.userId,challenge.hwid,timestamp,config.SECRET_KEY);const chunks=[];for(let i=0;i<wrapped.length;i+=1500){const chunk=wrapped.substring(i,i+1500);const enc=[];for(let j=0;j<chunk.length;j++)enc.push(chunk.charCodeAt(j)^key.charCodeAt(j%key.length));chunks.push(enc)}await logAccess(r,'SCRIPT_ENC',true,{userId:challenge.userId});res.json({success:true,mode:'encrypted',key,chunks,sessionId,ownerIds:config.OWNER_USER_IDS,whitelistIds:config.WHITELIST_USER_IDS})});
app.post('/api/heartbeat',async(r,res)=>{const{sessionId,hwid}=r.body;if(!sessionId||!hwid)return res.json({action:'TERMINATE'});const session=SESSIONS.get(sessionId);if(!session||session.hwid!==hwid)return res.json({action:'TERMINATE'});const ban=await db.isBanned(hwid,getIP(r),null);if(ban.blocked)return res.json({action:'TERMINATE'});session.lastSeen=Date.now();res.json({success:true,action:'CONTINUE'})});
app.post('/api/ban',async(r,res)=>{const{hwid,playerId,reason,toolsDetected,sessionId}=r.body;if(!hwid&&!playerId)return res.status(400).json({error:'Missing id'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();const data={hwid,ip:getIP(r),playerId,reason:reason||'Auto',toolsDetected:toolsDetected||[],banId,ts:new Date().toISOString()};if(hwid)await db.addBan(hwid,data);if(playerId)await db.addBan(String(playerId),data);if(sessionId)SESSIONS.delete(sessionId);res.json({success:true,banId})});
app.get('/api/admin/stats',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const stats=await db.getStats();res.json({success:true,stats,sessions:SESSIONS.size})});
app.get('/api/admin/logs',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const logs=await db.getLogs(Math.min(parseInt(r.query.limit)||50,500));res.json({success:true,logs})});
app.get('/api/admin/bans',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});res.json({success:true,bans:await db.getAllBans()})});
app.delete('/api/admin/bans/:id',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const bans=await db.getAllBans();const found=bans.find(b=>b.banId===r.params.id);if(found){await db.removeBan(found.key);return res.json({success:true})}res.status(404).json({error:'Not found'})});
app.post('/api/admin/bans',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const{hwid,ip,playerId,reason}=r.body;if(!hwid&&!ip&&!playerId)return res.status(400).json({error:'Required'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();const data={hwid,ip,playerId,reason:reason||'Manual',banId,ts:new Date().toISOString()};if(hwid)await db.addBan(hwid,data);if(playerId)await db.addBan(String(playerId),data);if(ip)await db.addBan(ip,data);res.json({success:true,banId})});
app.post('/api/admin/cache/clear',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});await db.setCachedScript(null);res.json({success:true})});
app.use('*',async(r,res)=>{const chk=isValidRequest(r);if(!chk.valid){return chk.reason==='browser'?res.status(404).type('html').send(TRAP_HTML):res.type('text/plain').send(genFakeScript())}res.status(404).json({error:'Not found'})});
setInterval(()=>{const now=Date.now();for(const[k,v]of NONCES)if(now-v>120000)NONCES.delete(k);for(const[k,v]of SESSIONS)if(now-v.created>3600000)SESSIONS.delete(k)},60000);
app.listen(process.env.PORT||3000,'0.0.0.0');
