const express=require('express'),axios=require('axios'),crypto=require('crypto'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),config=require('./config'),db=require('./lib/redis');
const app=express(),NONCES=new Map(),SESSIONS=new Map(),FAILED=new Map(),BLOCKED_PATTERNS=['pastebin.com','hastebin','ghostbin','rentry.co','paste.ee','controlc','textbin','codepad','ideone','replit.com','glitch.com','codepen','jsfiddle','raw.githubusercontent','gist.github','cdn.discord','media.discord','paste.ofcode','dpaste','bpaste','sprunge','ix.io','termbin','0x0.st','transfer.sh','file.io','tmpfiles','anonfiles','bayfiles','letsupload','megaup','uploadhaven'];
const EXECUTOR_SIGS=['synapse','script-ware','scriptware','fluxus','krnl','oxygen','evon','arceus','hydrogen','vegax','trigon','comet','solara','wave','zorara','codex','celery','swift','sirhurt','electron','sentinel','delta','coco','temple','valyse','nihon','roblox','wininet','executor','exploit','jjsploit','wearedevs'];
const BOT_PATTERNS=['bot','crawler','spider','scraper','curl','wget','python','node-fetch','axios','fetch','httpx','aiohttp','requests','postman','insomnia','discord','telegram','slack','whatsapp','facebook','twitter','java','okhttp','apache','libwww','perl','ruby','php','go-http','got/','undici','needle','superagent','guzzle','scrapy','beautifulsoup','selenium','puppeteer','playwright','mechanize','urllib','http.client','httplib','pycurl','treq','grequests','httpcore','niquests'];
const BROWSER_SIGS=['mozilla/','chrome/','safari/','firefox/','edge/','opera/','msie','trident/','webkit/','gecko/','chromium/','brave/','vivaldi/','yandex/','ucbrowser','samsungbrowser','qqbrowser','baidubrowser'];
const TRAP_HTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="refresh" content="0;url=https://www.google.com/search?q=roblox"><title>Redirecting...</title><style>*{margin:0;padding:0}body{background:#000;color:#fff;font-family:system-ui;display:flex;justify-content:center;align-items:center;height:100vh;flex-direction:column}@keyframes s{0%{transform:rotate(0)}100%{transform:rotate(360deg)}}.l{width:40px;height:40px;border:3px solid #333;border-top-color:#fff;border-radius:50%;animation:s 1s linear infinite;margin-bottom:20px}</style><script>!function(){var t=["https://google.com","https://youtube.com","https://roblox.com","about:blank"];setTimeout(function(){location.href=t[Math.floor(Math.random()*t.length)]},500+1500*Math.random());document.addEventListener("contextmenu",function(e){e.preventDefault()});document.addEventListener("keydown",function(e){(e.ctrlKey&&e.shiftKey&&"I"===e.key||"F12"===e.key)&&(e.preventDefault(),location.href="about:blank")})}();</script></head><body><div class="l"></div><p>Loading...</p></body></html>`;
function sha256(s){return crypto.createHash('sha256').update(s).digest('hex')}
function hmac(d,k){return crypto.createHmac('sha256',k).update(d).digest('hex')}
function secureCompare(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;try{return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))}catch{return false}}
function getIP(r){return(r.headers['x-forwarded-for']||'').split(',')[0].trim()||r.headers['x-real-ip']||r.ip||'0.0.0.0'}
function getHWID(r){return r.headers['x-hwid']||r.headers['x-hardware-id']||null}
function genNonce(){const n=crypto.randomBytes(24).toString('hex');NONCES.set(n,Date.now());return n}
function validateNonce(n){if(!n||!NONCES.has(n))return false;const t=NONCES.get(n);NONCES.delete(n);return Date.now()-t<60000}
function genSessionKey(u,h,t,s){return hmac(`${u}:${h}:${t}:${Math.floor(t/3600)}`,s).substring(0,32)}
function trackFailed(ip){const c=(FAILED.get(ip)||0)+1;FAILED.set(ip,c);if(c>15){db.addBan(ip,{ip,reason:'Too many failed attempts',ts:new Date().toISOString(),auto:true});return true}return false}
function genFakeScript(){const r=l=>{let s='';const c='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_';for(let i=0;i<l;i++)s+=c[Math.floor(Math.random()*c.length)];return s};const h=()=>{let x='';for(let i=0;i<Math.floor(Math.random()*20)+8;i++)x+='\\'+Math.floor(Math.random()*255);return x};const v=Array.from({length:30},()=>r(Math.floor(Math.random()*6)+2));const f=Array.from({length:120},()=>`"${h()}"`).join(',');const t=Array.from({length:60},()=>`[${Math.floor(Math.random()*99999)}]="${r(12)}"`).join(',');return`local ${v[0]}=(function()local ${v[1]}={${f}};local ${v[2]}={${t}};local ${v[3]}=0;for ${v[4]}=1,#${v[1]} do ${v[3]}=${v[3]}+((string.byte(${v[1]}[${v[4]}]:sub(1,1))or 0)%256)end;return ${v[3]} end)();local ${v[5]}=coroutine.wrap(function()for ${v[6]}=1,${Math.floor(Math.random()*99999)} do local ${v[7]}=bit32.bxor(${v[6]},${Math.floor(Math.random()*99999)})coroutine.yield(${v[7]})end end);local ${v[8]}=setmetatable({${t}},{__index=function(t,k)return rawget(t,k)or"${r(20)}"end,__newindex=function()end});(function()local ${v[9]}={}for ${v[10]}=1,math.random(80,200)do ${v[9]}[${v[10]}]=string.rep("${r(6)}",math.random(8,30)):reverse()end end)();pcall(function()local ${v[11]}=0 while ${v[11]}<150 do local ${v[12]}=${v[5]}()if not ${v[12]} then break end;${v[11]}=${v[11]}+1 end end);local ${v[13]}=function()local ${v[14]}={}for i=1,50 do ${v[14]}[i]=string.char(math.random(65,122))end;return table.concat(${v[14]})end;for i=1,20 do pcall(${v[13]})end;`}
function isValidExecutor(r){const ua=(r.headers['user-agent']||'').toLowerCase();const hasExecUA=EXECUTOR_SIGS.some(e=>ua.includes(e));const hasRobloxH=r.headers['x-roblox-id']&&r.headers['x-place-id']&&r.headers['x-job-id'];const hasExecToken=r.headers['x-executor-token'];const hasHWID=r.headers['x-hwid'];const hasSecretH=r.headers['x-script-version']||r.headers['x-loader-id'];const hasNonce=r.headers['x-nonce'];const noReferer=!r.headers['referer']&&!r.headers['origin'];const noCookie=!r.headers['cookie'];const noLang=!r.headers['accept-language'];const noSecFetch=!r.headers['sec-fetch-mode']&&!r.headers['sec-fetch-dest']&&!r.headers['sec-ch-ua'];const score=(hasExecUA?25:0)+(hasRobloxH?25:0)+(hasExecToken?15:0)+(hasHWID?15:0)+(hasSecretH?5:0)+(hasNonce?5:0)+(noReferer?3:0)+(noCookie?3:0)+(noLang?2:0)+(noSecFetch?2:0);return score>=40}
function isBrowser(r){if(isValidExecutor(r))return false;const ua=(r.headers['user-agent']||'').toLowerCase();const accept=r.headers['accept']||'';const hasBrowserUA=BROWSER_SIGS.some(b=>ua.includes(b));const hasBrowserAccept=accept.includes('text/html')&&accept.includes('application/xhtml');const hasBrowserHeaders=r.headers['accept-language']&&(r.headers['sec-fetch-dest']||r.headers['sec-fetch-mode']||r.headers['sec-ch-ua']||r.headers['upgrade-insecure-requests']);const hasReferer=!!r.headers['referer'];const hasOrigin=!!r.headers['origin'];return hasBrowserUA||(hasBrowserAccept&&hasBrowserHeaders)||(hasReferer&&hasBrowserUA)||(hasOrigin&&hasBrowserUA)}
function isBot(r){if(isValidExecutor(r))return false;const ua=(r.headers['user-agent']||'').toLowerCase();const accept=r.headers['accept']||'';if(BOT_PATTERNS.some(p=>ua.includes(p)))return true;if(!ua||ua.length<15)return true;if(ua==='mozilla/5.0'||ua==='python-requests')return true;if(r.headers['sec-fetch-dest']||r.headers['sec-fetch-mode']||r.headers['sec-ch-ua'])return true;if(r.headers['referer']||r.headers['origin'])return true;if(r.headers['cookie'])return true;if(accept.includes('text/html')&&!EXECUTOR_SIGS.some(e=>ua.includes(e)))return true;const hasBrowserUA=BROWSER_SIGS.some(b=>ua.includes(b));const hasExecUA=EXECUTOR_SIGS.some(e=>ua.includes(e));if(hasBrowserUA&&!hasExecUA)return true;if(r.headers['dnt']||r.headers['x-requested-with']==='XMLHttpRequest')return true;const ct=r.headers['content-type']||'';if(r.method==='POST'&&!ct.includes('application/json'))return true;return false}
function isUrlLeak(r){const body=JSON.stringify(r.body||{}).toLowerCase();const query=JSON.stringify(r.query||{}).toLowerCase();const combined=body+query;return BLOCKED_PATTERNS.some(p=>combined.includes(p))}
function containsSuspiciousContent(r){const body=JSON.stringify(r.body||{}).toLowerCase();const suspicious=['eval(','loadstring(','http.request','syn.request','getgenv()','getfenv()','debug.','hookfunction','hookmetamethod','getgc()','getreg()','getrawmetatable','setreadonly','saveinstance','decompile','dumpstring','request({'];return suspicious.some(s=>body.includes(s))}
async function logAccess(r,a,s,d={}){const log={ip:getIP(r),hwid:getHWID(r),pid:r.headers['x-player-id'],ua:(r.headers['user-agent']||'').substring(0,100),action:a,success:s,path:r.path,ts:new Date().toISOString(),...d};await db.addLog(log);return log}
function genChallenge(){const types=['math','bitwise','sequence','xor'];const type=types[Math.floor(Math.random()*types.length)];switch(type){case'math':const ops=['+','-','*'];const op=ops[Math.floor(Math.random()*ops.length)];const a=Math.floor(Math.random()*50)+10,b=Math.floor(Math.random()*20)+5,c=Math.floor(Math.random()*10)+1;let ans;switch(op){case'+':ans=(a+b)*c;break;case'-':ans=(a-b)*c;break;case'*':ans=(a*b)+c;break}return{type:'math',puzzle:{a,b,c,op},answer:ans};case'bitwise':const x=Math.floor(Math.random()*200)+50,y=Math.floor(Math.random()*100)+20;const bops=['xor','and','or'];const bop=bops[Math.floor(Math.random()*bops.length)];let bans;switch(bop){case'xor':bans=x^y;break;case'and':bans=x&y;break;case'or':bans=x|y;break}return{type:'bitwise',puzzle:{x,y,op:bop},answer:bans};case'sequence':const start=Math.floor(Math.random()*15)+1,step=Math.floor(Math.random()*8)+2;const seq=[start,start+step,start+step*2,start+step*3];return{type:'sequence',puzzle:{seq},answer:start+step*4};case'xor':const nums=Array.from({length:4},()=>Math.floor(Math.random()*100)+10);const xorAns=nums.reduce((a,b)=>a^b,0);return{type:'xor',puzzle:{nums},answer:xorAns};default:const simple=Array.from({length:5},()=>Math.floor(Math.random()*50)+1);return{type:'sum',puzzle:{numbers:simple},answer:simple.reduce((a,b)=>a+b,0)}}}
function isObfuscated(s){if(!s)return false;return[/IronBrew/i,/Prometheus/i,/Moonsec/i,/Luraph/i,/PSU/i,/Bytecode/i,/-- Obfuscated/i,/--\[\[Obfuscated/i].some(r=>r.test(s.substring(0,600)))}
async function getScript(){const cached=await db.getCachedScript();if(cached)return cached;if(!config.SCRIPT_SOURCE_URL)return null;try{const res=await axios.get(config.SCRIPT_SOURCE_URL,{timeout:15000,headers:{'User-Agent':'Roblox/WinInet','Accept':'*/*'}});if(typeof res.data==='string'&&res.data.length>50){await db.setCachedScript(res.data);return res.data}}catch{}return null}
function wrapScript(script,serverUrl){const o=config.OWNER_USER_IDS.join(','),w=config.WHITELIST_USER_IDS.join(','),b=`${serverUrl}/api/ban`,hb=`${serverUrl}/api/heartbeat`;return`local _O={${o}} local _W={${w}} local _B="${b}" local _HB="${hb}" local _P=game:GetService("Players") local _L=_P.LocalPlayer local _S=game:GetService("StarterGui") local _C=game:GetService("CoreGui") local _H=game:GetService("HttpService") local _TS=game:GetService("TeleportService") local _RS=game:GetService("RunService") local _A=true local _SD=false local _CON={} local _THR={} local _RDY=false local _SID="${crypto.randomBytes(16).toString('hex')}"
local _IT={g={},m={}}
local _PG=nil
pcall(function() _PG=_L:FindFirstChild("PlayerGui") or _L:WaitForChild("PlayerGui",3) end)
local function _isW(u) if not _W or #_W==0 then return false end for _,i in ipairs(_W) do if u==i then return true end end return false end
local function _isO(u) if not _O or #_O==0 then return false end for _,i in ipairs(_O) do if u==i then return true end end return false end
local function _n(t,x,d) pcall(function() _S:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3}) end) end
local function _hw() local s,r=pcall(function() if gethwid then return gethwid() end if get_hwid then return get_hwid() end if getexecutorname and identifyexecutor then return tostring(identifyexecutor()).."_"..tostring(_L.UserId) end return "FB_"..tostring(_L.UserId) end) return s and r or "UNK" end
local function _hp(u,d,m) local r=(syn and syn.request) or request or http_request or (http and http.request) if not r then return nil end m=m or"POST" local ok,res=pcall(function() return r({Url=u,Method=m,Headers={["Content-Type"]="application/json",["User-Agent"]="Roblox/WinInet",["x-hwid"]=_hw(),["x-roblox-id"]=tostring(_L.UserId),["x-place-id"]=tostring(game.PlaceId),["x-job-id"]=game.JobId,["x-session-id"]=_SID},Body=d and _H:JSONEncode(d) or nil}) end) if not ok then return nil end if res.StatusCode~=200 then return nil end local ps,pd=pcall(function() return _H:JSONDecode(res.Body) end) return ps and pd or nil end
local function _freeze() pcall(function() local sc=Instance.new("ScreenGui") sc.Name="X"..math.random(100000,999999) sc.IgnoreGuiInset=true sc.DisplayOrder=2147483647 sc.ResetOnSpawn=false sc.Parent=_C local fr=Instance.new("Frame") fr.Size=UDim2.new(1,0,1,0) fr.BackgroundColor3=Color3.new(0,0,0) fr.BorderSizePixel=0 fr.Parent=sc local tx=Instance.new("TextLabel") tx.Size=UDim2.new(1,0,1,0) tx.BackgroundTransparency=1 tx.Text="ACCESS DENIED" tx.TextColor3=Color3.new(1,0,0) tx.TextSize=48 tx.Font=Enum.Font.GothamBold tx.Parent=fr end) end
local function _fd(reason) _A=false _RDY=false _freeze() task.delay(0.5,function() pcall(function() _L:Kick(reason) end) task.wait(0.3) pcall(function() _TS:Teleport(9999999999) end) task.wait(0.3) pcall(function() while true do end end) end) end
local function _ban(rs,t) if _SD then return end _SD=true _A=false _hp(_B,{hwid=_hw(),playerId=_L.UserId,playerName=_L.Name,reason=rs,toolsDetected=t or {},sessionId=_SID}) _n("⛔","Banned: "..rs,5) _fd(rs) end
local function _cl() if _SD then return end _SD=true _A=false _RDY=false for i=#_THR,1,-1 do pcall(task.cancel,_THR[i]) end for i=#_CON,1,-1 do pcall(function() _CON[i]:Disconnect() end) end _THR={} _CON={} end
_G._SCRIPT_CLEANUP=_cl
local _TP={"simplespy","httpspy","remotespy","hydroxide","infiniteyield","infinite_yield","serverspy","scriptdumper","frosthook","hookspy","darkdex","dex_explorer","unitedhub","iy_topbar","iy_main","saveinstance","dumper","spy","sniper","logger","grabber","stealer"}
local _TM={"SimpleSpy","HttpSpy","RemoteSpy","Hydroxide","Dex","DexExplorer","InfiniteYield","IY_LOADED","SimpleSpyExecuted","RemoteSpyLoaded","InfiniteYieldLoaded","HYDROXIDE_LOADED","DEX_EXPLORER","ScriptDumperLoaded"}
local function _detectHook() local e=getgenv and getgenv() or _G local hooked={} if loadstring~=_G.loadstring then table.insert(hooked,"loadstring") end if getgc and type(getgc)=="function" then local s,r=pcall(getgc) if not s then table.insert(hooked,"getgc") end end if getreg and type(getreg)=="function" then local s,r=pcall(getreg) if not s then table.insert(hooked,"getreg") end end if syn and syn.request then local mt=getmetatable(syn.request) if mt and mt.__call then table.insert(hooked,"syn.request") end end return hooked end
local function _antiDebug() if not debug then return end local _od={} pcall(function() _od.gi=debug.getinfo _od.gu=debug.getupvalue _od.su=debug.setupvalue _od.gl=debug.getlocal _od.sl=debug.setlocal end) if newcclosure then debug.getupvalue=newcclosure(function() return nil,nil end) debug.setupvalue=newcclosure(function() return nil end) debug.getlocal=newcclosure(function() return "x",nil end) debug.setlocal=newcclosure(function() return nil end) debug.getinfo=newcclosure(function(f,w) if type(f)=="function" then return{source="[C]",short_src="[C]",what="C",linedefined=0,lastlinedefined=0,nups=0,nparams=0,isvararg=false,name="",namewhat=""} end if _od.gi then return _od.gi(f,w) end return nil end) end end
local function _antiGC() if not getgc or not newcclosure then return end local _ogc=getgc local callCount=0 getgc=newcclosure(function(inc) callCount=callCount+1 if callCount>20 then _ban("GC abuse",{"getgc",callCount}) return {} end local ok,r=pcall(_ogc,inc) if not ok then return {} end local c={} for i,v in pairs(r) do if type(v)~="function" then c[#c+1]=v end end return c end) end
local function _antiReg() if not getreg or not newcclosure then return end local _oreg=getreg local callCount=0 getreg=newcclosure(function() callCount=callCount+1 if callCount>10 then _ban("Registry abuse",{"getreg",callCount}) return {} end return {} end) end
local function _doSnap() local e=getgenv and getgenv() or _G for _,m in ipairs(_TM) do local v=rawget(e,m) if v~=nil then _IT.m[m]=true end end local ok,g=pcall(function() return rawget(e,"_G") end) if ok and g and type(g)=="table" then for _,k in ipairs({"SimpleSpy","RemoteSpy","HttpSpy","Dex","InfiniteYield","IY_LOADED"}) do if rawget(g,k) then _IT.m["G_"..k]=true end end end if _C then pcall(function() for _,gui in pairs(_C:GetChildren()) do if gui:IsA("ScreenGui") or gui:IsA("Folder") or gui:IsA("Frame") then _IT.g[gui.Name:lower()]=true end end end) end if _PG then pcall(function() for _,gui in pairs(_PG:GetChildren()) do if gui:IsA("ScreenGui") or gui:IsA("Folder") or gui:IsA("Frame") then _IT.g[gui.Name:lower()]=true end end end) end if gethui then pcall(function() for _,gui in pairs(gethui():GetChildren()) do _IT.g[gui.Name:lower()]=true end end) end end
local function _snap() if _isW(_L.UserId) then _RDY=true return end _doSnap() task.wait(0.5) _doSnap() task.wait(0.5) _doSnap() _RDY=true end
local function _chkNew(n,isM) if isM then return _IT.m[n]==nil else return _IT.g[n:lower()]==nil end end
local function _det() if not _RDY or not _A or _isW(_L.UserId) then return false end local e=getgenv and getgenv() or _G for _,m in ipairs(_TM) do local ok,v=pcall(function() return rawget(e,m) end) if ok and v~=nil and _chkNew(m,true) then return true,"ENV",m end end local ok2,g=pcall(function() return rawget(e,"_G") end) if ok2 and g and type(g)=="table" then for _,k in ipairs({"SimpleSpy","RemoteSpy","HttpSpy","Dex","InfiniteYield","IY_LOADED","SimpleSpyExecuted"}) do local key="G_"..k local ok3,val=pcall(function() return rawget(g,k) end) if ok3 and val and _chkNew(key,true) then return true,"_G",k end end end local function chkGui(parent,pname) if not parent then return false,nil,nil end local found,sig for _,gui in pairs(parent:GetChildren()) do if gui:IsA("ScreenGui") or gui:IsA("Folder") then local nm=gui.Name:lower() if _chkNew(nm,false) then for _,p in ipairs(_TP) do if nm:find(p,1,true) then return true,pname,gui.Name end end end end end return false,nil,nil end local f1,c1,s1=chkGui(_C,"CoreGui") if f1 then return f1,c1,s1 end local f2,c2,s2=chkGui(_PG,"PlayerGui") if f2 then return f2,c2,s2 end if gethui then local f3,c3,s3=chkGui(gethui(),"HiddenUI") if f3 then return f3,c3,s3 end end return false end
local function _mon() if _isW(_L.UserId) then return end local th=task.spawn(function() while not _RDY do task.wait(0.3) end local hooks=_detectHook() if #hooks>0 then _ban("Hooks: "..table.concat(hooks,","),hooks) return end task.wait(3) while _A and not _SD do task.wait(15) if not _A or _SD then break end local d,c,s=_det() if d then _ban("Tool: "..(s or c),{c,s}) break end end end) table.insert(_THR,th) end
local function _watchGui() if _isW(_L.UserId) then return end local function chk(gui) if not _A or _SD or not _RDY then return end if not gui:IsA("ScreenGui") and not gui:IsA("Folder") then return end task.delay(1.5,function() if not _A or _SD or not _RDY then return end local nm=gui.Name:lower() if _chkNew(nm,false) then for _,p in ipairs(_TP) do if nm:find(p,1,true) then _ban("Tool: "..gui.Name,{"GUI",gui.Name}) return end end end end) end if _C then local c1=_C.ChildAdded:Connect(chk) table.insert(_CON,c1) end if _PG then local c2=_PG.ChildAdded:Connect(chk) table.insert(_CON,c2) end if gethui then pcall(function() local c3=gethui().ChildAdded:Connect(chk) table.insert(_CON,c3) end) end end
local function _heartbeat() local th=task.spawn(function() task.wait(10) while _A and not _SD do task.wait(25) if not _A or _SD then break end local res=_hp(_HB,{sessionId=_SID,hwid=_hw(),timestamp=os.time()}) if res and res.action=="TERMINATE" then _ban("Session terminated",{"heartbeat"}) break end if res and res.action=="WARN" then _n("⚠️",res.message or "Warning",3) end end end) table.insert(_THR,th) end
local function _ownerOk() if not _O or #_O==0 then return true end for _,p in pairs(_P:GetPlayers()) do if _isO(p.UserId) and p~=_L then return false end end return true end
local function _ownerMon() if not _O or #_O==0 then return end local th=task.spawn(function() while _A and not _SD do task.wait(20) if not _A or _SD then break end if not _ownerOk() then _n("⚠️","Owner detected",3) _cl() return end end end) table.insert(_THR,th) local cn=_P.PlayerAdded:Connect(function(p) if not _A or _SD then return end task.wait(1) if _isO(p.UserId) then _n("⚠️","Owner joined",3) _cl() end end) table.insert(_CON,cn) end
if not _ownerOk() then _n("⚠️","Owner in server",3) return end
task.spawn(function() _antiDebug() _antiGC() _antiReg() _snap() _mon() _watchGui() _ownerMon() _heartbeat() end)
${script}`}
function getLoader(serverUrl){return`local S="${serverUrl}" local H=game:GetService("HttpService") local P=game:GetService("Players") local G=game:GetService("StarterGui") local L=P.LocalPlayer local A=true local _PF={}
_PF.req=(syn and syn.request) or request or http_request or (http and http.request)
_PF.ls=loadstring
local function n(t,x,d) pcall(function() G:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3}) end) end
local function hw() local s,r=pcall(function() if gethwid then return gethwid() end if get_hwid then return get_hwid() end return "FB_"..tostring(L.UserId) end) return s and r or "UNK" end
local function ex() local s,r=pcall(function() if identifyexecutor then return (identifyexecutor()) end if getexecutorname then return getexecutorname() end return "Unknown" end) return s and r or "Unknown" end
local function chkHooks() local h={} if loadstring~=_PF.ls then table.insert(h,"loadstring") end if syn and syn.request~=_PF.req then table.insert(h,"request") end return h end
local function hp(u,d,hd) if not _PF.req then return nil end hd=hd or {} hd["Content-Type"]="application/json" hd["User-Agent"]="Roblox/WinInet" hd["x-hwid"]=hw() hd["x-roblox-id"]=tostring(L.UserId) hd["x-place-id"]=tostring(game.PlaceId) hd["x-job-id"]=game.JobId hd["x-executor-token"]=ex() hd["x-nonce"]=tostring(math.random(100000000,999999999))..tostring(tick()) local s,res=pcall(function() return _PF.req({Url=u,Method="POST",Headers=hd,Body=H:JSONEncode(d)}) end) if not s then return nil end if res.StatusCode~=200 then local e pcall(function() e=H:JSONDecode(res.Body) end) return e end local ps,pd=pcall(function() return H:JSONDecode(res.Body) end) return ps and pd or nil end
local function xd(d,k) local r={} for i=1,#d do r[i]=string.char(bit32.bxor(d[i],string.byte(k,((i-1)%#k)+1))) end return table.concat(r) end
local function solve(p) if p.type=="math" then local a,b,c,op=p.puzzle.a,p.puzzle.b,p.puzzle.c,p.puzzle.op if op=="+" then return(a+b)*c elseif op=="-" then return(a-b)*c elseif op=="*" then return(a*b)+c end elseif p.type=="bitwise" then local x,y,op=p.puzzle.x,p.puzzle.y,p.puzzle.op if op=="xor" then return bit32.bxor(x,y) elseif op=="and" then return bit32.band(x,y) elseif op=="or" then return bit32.bor(x,y) end elseif p.type=="sequence" then local s=p.puzzle.seq local step=s[2]-s[1] return s[4]+step elseif p.type=="xor" then local r=0 for _,v in ipairs(p.puzzle.nums) do r=bit32.bxor(r,v) end return r elseif p.numbers then local sum=0 for _,x in ipairs(p.numbers) do sum=sum+x end return sum end return 0 end
local T=nil
local function reg() local r=hp(S.."/api/executor/register",{robloxId=L.UserId,placeId=game.PlaceId,jobId=game.JobId,hwid=hw(),executor=ex()}) if r and r.success then T=r.token end end
local function op(o) if not o or #o==0 then return true end local function io(u) for _,i in ipairs(o) do if u==i then return true end end return false end local function co() for _,p in pairs(P:GetPlayers()) do if io(p.UserId) and p~=L then return true,p.Name end end return false end local op,on=co() if op then n("⚠️","Owner ("..on..") here",5) return false end task.spawn(function() while A and task.wait(12) do local pr,nm=co() if pr then A=false if _G._SCRIPT_CLEANUP then pcall(_G._SCRIPT_CLEANUP) end n("⚠️","Owner detected",3) break end end end) P.PlayerAdded:Connect(function(p) task.wait(0.5) if A and io(p.UserId) then A=false if _G._SCRIPT_CLEANUP then pcall(_G._SCRIPT_CLEANUP) end n("⚠️","Owner joined",3) end end) return true end
local function m() local hooks=chkHooks() if #hooks>0 then n("❌","Security violation",5) hp(S.."/api/ban",{hwid=hw(),playerId=L.UserId,reason="Hooks: "..table.concat(hooks,","),toolsDetected=hooks}) task.wait(1) L:Kick("Security violation") return end reg() n("🔄","Connecting...",2) local h={} if T then h["x-executor-token"]=T end local c=hp(S.."/api/auth/challenge",{userId=L.UserId,hwid=hw(),placeId=game.PlaceId},h) if not c then n("❌","Connection failed",5) return end if not c.success then n("❌",c.error or "Error",5) if c.error and c.error:find("Banned") then task.wait(1) L:Kick("⛔ Banned") end return end local sol=solve(c) n("🔄","Verifying...",2) local v=hp(S.."/api/auth/verify",{challengeId=c.challengeId,solution=sol,timestamp=os.time()},h) if not v or not v.success then n("❌",v and v.error or "Failed",5) return end n("✅","Loading...",2) if not op(v.ownerIds) then return end local fs if v.mode=="raw" then fs=v.script else local p={} for i,ch in ipairs(v.chunks) do p[i]=xd(ch,v.key) end fs=table.concat(p) end local fn=_PF.ls(fs) if fn then fs=nil v=nil c=nil pcall(fn) end end
pcall(m)`}
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false,crossOriginResourcePolicy:false}));
app.use(cors({origin:'*',methods:['GET','POST','DELETE','OPTIONS'],allowedHeaders:['Content-Type','x-admin-key','x-hwid','x-player-id','x-executor-token','x-roblox-id','x-place-id','x-job-id','x-nonce','x-session-id','x-script-version','x-loader-id','x-timestamp','x-signature']}));
app.use(express.json({limit:'2mb'}));
app.set('trust proxy',1);
const limiter=rateLimit({windowMs:60000,max:80,keyGenerator:(r)=>getIP(r),handler:(r,res)=>{trackFailed(getIP(r));res.status(429).json({error:'Rate limited'})}});
app.use(limiter);
app.use(async(req,res,next)=>{const ip=getIP(req);const ban=await db.isBanned(null,ip,null);if(ban.blocked){if(isBrowser(req))return res.status(403).type('html').send(TRAP_HTML);return res.status(403).json({error:'Blocked'})}if(isUrlLeak(req)){await logAccess(req,'URL_LEAK',false);trackFailed(ip);if(isBrowser(req))return res.status(403).type('html').send(TRAP_HTML);return res.type('text/plain').send(genFakeScript())}if(containsSuspiciousContent(req)){await logAccess(req,'SUSPICIOUS',false);trackFailed(ip)}next()});
app.get('/',async(r,res)=>{if(isBrowser(r))return res.status(403).type('html').send(TRAP_HTML);if(isBot(r)){await logAccess(r,'BOT_ROOT',false);return res.type('text/plain').send(genFakeScript())}if(!isValidExecutor(r)){await logAccess(r,'UNKNOWN_ROOT',false);return res.type('text/plain').send(genFakeScript())}res.json({s:'ok',v:'6.0.0',t:Date.now()})});
app.get('/health',(r,res)=>res.json({status:'ok'}));
app.get(['/loader','/api/loader.lua','/api/loader','/l'],async(r,res)=>{if(isBrowser(r))return res.status(403).type('html').send(TRAP_HTML);if(isBot(r)||!isValidExecutor(r)){await logAccess(r,'BOT_LOADER',false);return res.type('text/plain').send(genFakeScript())}await logAccess(r,'LOADER',true);const url=process.env.RENDER_EXTERNAL_URL||`${r.protocol}://${r.get('host')}`;res.type('text/plain').send(getLoader(url))});
app.post('/api/executor/register',async(r,res)=>{if(isBrowser(r))return res.status(403).json({error:'Forbidden'});if(isBot(r)){await logAccess(r,'BOT_REG',false);return res.status(403).json({error:'Invalid'})}const{robloxId,placeId,jobId,hwid,executor}=r.body;if(!robloxId||!placeId||!jobId)return res.status(400).json({error:'Missing fields'});const token=crypto.randomBytes(32).toString('hex');const nonce=genNonce();await db.setToken(token,{robloxId,placeId,jobId,hwid,executor,ip:getIP(r),created:Date.now(),nonce},300);await logAccess(r,'REGISTER',true,{robloxId});res.json({success:true,token,nonce,expiresIn:300})});
app.post('/api/auth/challenge',async(r,res)=>{if(isBrowser(r))return res.status(403).json({error:'Forbidden'});if(isBot(r)&&!r.headers['x-executor-token']&&!r.headers['x-hwid']){await logAccess(r,'BOT_CHAL',false);return res.status(403).json({error:'Invalid client'})}const{userId,hwid,placeId}=r.body;if(!userId||!hwid||!placeId)return res.status(400).json({error:'Missing fields'});const uid=parseInt(userId),pid=parseInt(placeId);if(isNaN(uid)||isNaN(pid))return res.status(400).json({error:'Invalid format'});const ip=getIP(r);const ban=await db.isBanned(hwid,ip,uid);if(ban.blocked)return res.status(403).json({success:false,error:'Banned: '+ban.reason,banId:ban.banId});if(config.ALLOWED_PLACE_IDS.length>0&&!config.ALLOWED_PLACE_IDS.includes(pid))return res.status(403).json({error:'Game not allowed'});const id=crypto.randomBytes(16).toString('hex');const nonce=genNonce();const chal=genChallenge();const challenge={id,nonce,userId:uid,hwid,placeId:pid,ip,...chal};await db.setChallenge(id,challenge,45);await logAccess(r,'CHALLENGE',true,{id,userId:uid});res.json({success:true,challengeId:id,nonce,type:chal.type,puzzle:chal.puzzle,expiresIn:45})});
app.post('/api/auth/verify',async(r,res)=>{if(isBrowser(r))return res.status(403).json({error:'Forbidden'});if(isBot(r)&&!r.headers['x-executor-token']&&!r.headers['x-hwid']){await logAccess(r,'BOT_VER',false);return res.status(403).json({error:'Invalid client'})}const{challengeId,solution,timestamp}=r.body;if(!challengeId||solution===undefined||!timestamp)return res.status(400).json({error:'Missing fields'});const challenge=await db.getChallenge(challengeId);if(!challenge)return res.status(403).json({error:'Expired'});const ip=getIP(r);if(challenge.ip!==ip){trackFailed(ip);return res.status(403).json({error:'IP mismatch'})}if(parseInt(solution)!==challenge.answer){trackFailed(ip);await logAccess(r,'WRONG_SOL',false,{expected:challenge.answer,got:solution});return res.status(403).json({error:'Wrong solution'})}await db.deleteChallenge(challengeId);const script=await getScript();if(!script)return res.status(500).json({error:'Script not configured'});const url=process.env.RENDER_EXTERNAL_URL||`${r.protocol}://${r.get('host')}`;const wrapped=wrapScript(script,url);const isObf=config.SCRIPT_ALREADY_OBFUSCATED||isObfuscated(script);const sessionId=crypto.randomBytes(16).toString('hex');SESSIONS.set(sessionId,{hwid:challenge.hwid,ip,userId:challenge.userId,created:Date.now()});if(isObf){await logAccess(r,'SCRIPT_RAW',true,{userId:challenge.userId});return res.json({success:true,mode:'raw',script:wrapped,sessionId,ownerIds:config.OWNER_USER_IDS,whitelistIds:config.WHITELIST_USER_IDS,meta:{userId:challenge.userId,placeId:challenge.placeId,ts:Date.now()}})}const key=genSessionKey(challenge.userId,challenge.hwid,timestamp,config.SECRET_KEY);const chunks=[];for(let i=0;i<wrapped.length;i+=1500){const chunk=wrapped.substring(i,i+1500);const enc=[];for(let j=0;j<chunk.length;j++)enc.push(chunk.charCodeAt(j)^key.charCodeAt(j%key.length));chunks.push(enc)}await logAccess(r,'SCRIPT_ENC',true,{userId:challenge.userId});res.json({success:true,mode:'encrypted',key,chunks,sessionId,checksum:sha256(wrapped).substring(0,16),ownerIds:config.OWNER_USER_IDS,whitelistIds:config.WHITELIST_USER_IDS,meta:{userId:challenge.userId,placeId:challenge.placeId,ts:Date.now()}})});
app.post('/api/heartbeat',async(r,res)=>{if(isBrowser(r)||isBot(r))return res.status(403).json({action:'TERMINATE'});const{sessionId,hwid,timestamp}=r.body;if(!sessionId||!hwid)return res.json({success:false,action:'TERMINATE'});const session=SESSIONS.get(sessionId);if(!session)return res.json({success:false,action:'TERMINATE',reason:'Session not found'});if(session.hwid!==hwid)return res.json({success:false,action:'TERMINATE',reason:'HWID mismatch'});if(session.ip!==getIP(r))return res.json({success:false,action:'WARN',message:'IP changed'});const ban=await db.isBanned(hwid,getIP(r),session.userId);if(ban.blocked)return res.json({success:false,action:'TERMINATE',reason:'Banned'});session.lastSeen=Date.now();res.json({success:true,action:'CONTINUE',nextBeat:25000})});
app.post('/api/ban',async(r,res)=>{const{hwid,playerId,playerName,reason,toolsDetected,sessionId}=r.body;if(!hwid&&!playerId)return res.status(400).json({error:'Missing id'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();const data={hwid,ip:getIP(r),playerId,playerName,reason:reason||'Auto',toolsDetected:toolsDetected||[],banId,sessionId,ts:new Date().toISOString()};if(hwid)await db.addBan(hwid,data);if(playerId)await db.addBan(String(playerId),data);await logAccess(r,'BAN',true,{playerId,reason,banId});if(sessionId)SESSIONS.delete(sessionId);res.json({success:true,banId})});
app.get('/api/admin/stats',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const stats=await db.getStats();res.json({success:true,stats,sessions:SESSIONS.size,nonces:NONCES.size,failed:FAILED.size})});
app.get('/api/admin/logs',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const limit=Math.min(parseInt(r.query.limit)||50,500);const logs=await db.getLogs(limit);res.json({success:true,count:logs.length,logs})});
app.get('/api/admin/bans',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const bans=await db.getAllBans();res.json({success:true,count:bans.length,bans})});
app.delete('/api/admin/bans/:banId',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const bans=await db.getAllBans();const found=bans.find(b=>b.banId===r.params.banId);if(found){await db.removeBan(found.key);return res.json({success:true})}res.status(404).json({error:'Not found'})});
app.post('/api/admin/bans',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const{hwid,ip,playerId,playerName,reason}=r.body;if(!hwid&&!ip&&!playerId)return res.status(400).json({error:'Identifier required'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();const data={hwid,ip,playerId,playerName,reason:reason||'Manual',banId,ts:new Date().toISOString(),by:'admin'};if(hwid)await db.addBan(hwid,data);if(playerId)await db.addBan(String(playerId),data);if(ip)await db.addBan(ip,data);res.json({success:true,banId})});
app.post('/api/admin/bans/clear',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const count=await db.clearBans();res.json({success:true,cleared:count})});
app.post('/api/admin/cache/clear',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});await db.setCachedScript(null);res.json({success:true})});
app.post('/api/admin/sessions/clear',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Invalid key'});const count=SESSIONS.size;SESSIONS.clear();res.json({success:true,cleared:count})});
app.use('*',async(r,res)=>{if(isBrowser(r))return res.status(404).type('html').send(TRAP_HTML);if(isBot(r)||!isValidExecutor(r)){await logAccess(r,'BOT_404',false);return res.type('text/plain').send(genFakeScript())}res.status(404).json({error:'Not found'})});
setInterval(()=>{const now=Date.now();for(const[k,v]of NONCES){if(now-v>120000)NONCES.delete(k)}for(const[k,v]of SESSIONS){if(now-v.created>3600000)SESSIONS.delete(k)}for(const[k,v]of FAILED){if(v>0)FAILED.set(k,Math.max(0,v-1))}},60000);
const PORT=process.env.PORT||3000;
app.listen(PORT,'0.0.0.0',()=>{});
