const express=require('express'),axios=require('axios'),crypto=require('crypto'),cors=require('cors'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),config=require('./config'),db=require('./lib/redis');
const app=express(),SESSIONS=new Map();
const BOT_UA=['python','curl','wget','axios','node-fetch','aiohttp','httpx','requests/','postman','insomnia','discord.','telegram','scrapy','selenium','puppeteer','java/','okhttp','perl','php/','ruby','go-http','got/','undici','urllib'];
const TRAP_HTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta http-equiv="refresh" content="1;url=https://google.com"><title>Redirecting</title><style>body{background:#000;color:#fff;display:flex;justify-content:center;align-items:center;height:100vh;font-family:sans-serif}</style></head><body><p>Redirecting...</p><script>setTimeout(()=>location.href='https://google.com',500)</script></body></html>`;
function sha256(s){return crypto.createHash('sha256').update(s).digest('hex')}
function hmac(d,k){return crypto.createHmac('sha256',k).update(d).digest('hex')}
function secureCompare(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;try{return crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))}catch{return false}}
function getIP(r){return(r.headers['x-forwarded-for']||'').split(',')[0].trim()||r.headers['x-real-ip']||r.ip||'0.0.0.0'}
function getHWID(r){return r.headers['x-hwid']||null}
function genSessionKey(u,h,t,s){return hmac(`${u}:${h}:${t}`,s).substring(0,32)}
function genFakeScript(){const v=()=>{let s='';for(let i=0;i<Math.floor(Math.random()*8)+4;i++)s+='abcdefghijklmnopqrstuvwxyz'[Math.floor(Math.random()*26)];return s};const h=()=>{let x='';for(let i=0;i<Math.floor(Math.random()*30)+15;i++)x+='\\'+Math.floor(Math.random()*255);return x};const vars=[];for(let i=0;i<40;i++)vars.push(v());const strs=[];for(let i=0;i<200;i++)strs.push('"'+h()+'"');const nums=[];for(let i=0;i<100;i++)nums.push('['+Math.floor(Math.random()*99999)+']="'+v()+'"');return`local ${vars[0]}=(function()local ${vars[1]}={${strs.slice(0,80).join(',')}};local ${vars[2]}={${nums.slice(0,40).join(',')}};local ${vars[3]}=0;for ${vars[4]}=1,#${vars[1]} do ${vars[3]}=${vars[3]}+((string.byte(${vars[1]}[${vars[4]}]:sub(1,1))or 0)%256)end;return ${vars[3]} end)();local ${vars[5]}=coroutine.wrap(function()for ${vars[6]}=1,${Math.floor(Math.random()*50000)+10000} do local ${vars[7]}=bit32.bxor(${vars[6]},${Math.floor(Math.random()*99999)})coroutine.yield(${vars[7]})end end);local ${vars[8]}=setmetatable({${nums.slice(40,80).join(',')}},{__index=function(t,k)return rawget(t,k)or"${v()}"end,__newindex=function()end});(function()local ${vars[9]}={}for ${vars[10]}=1,math.random(100,300)do ${vars[9]}[${vars[10]}]=string.rep("${v()}",math.random(10,40)):reverse()end end)();pcall(function()local ${vars[11]}=0 while ${vars[11]}<200 do local ${vars[12]}=${vars[5]}()if not ${vars[12]} then break end;${vars[11]}=${vars[11]}+1 end end);local ${vars[13]}={${strs.slice(80,160).join(',')}};local ${vars[14]}=function()local ${vars[15]}={}for i=1,80 do ${vars[15]}[i]=string.char(math.random(65,122))end;return table.concat(${vars[15]})end;for i=1,30 do pcall(${vars[14]})end;local ${vars[16]}=0;for _,v in pairs(${vars[13]})do ${vars[16]}=${vars[16]}+#v end;`}
function hasExecutorHeaders(r){return!!(r.headers['x-hwid']||r.headers['x-roblox-id']||r.headers['x-place-id']||r.headers['x-job-id'])}
function isBrowser(r){if(hasExecutorHeaders(r))return false;if(r.headers['sec-fetch-dest'])return true;if(r.headers['sec-fetch-mode'])return true;if(r.headers['sec-fetch-site'])return true;if(r.headers['sec-ch-ua'])return true;if(r.headers['sec-ch-ua-mobile'])return true;if(r.headers['upgrade-insecure-requests'])return true;const accept=r.headers['accept']||'';const ua=(r.headers['user-agent']||'').toLowerCase();const hasLang=!!r.headers['accept-language'];const hasCookie=!!r.headers['cookie'];if(accept.includes('text/html')&&hasLang&&(ua.includes('mozilla')||ua.includes('chrome')||ua.includes('safari')||ua.includes('firefox')||ua.includes('edge')))return true;return false}
function isBot(r){if(hasExecutorHeaders(r))return false;const ua=(r.headers['user-agent']||'').toLowerCase();if(!ua||ua.length<5)return true;if(ua==='mozilla/5.0')return true;if(BOT_UA.some(p=>ua.includes(p)))return true;if(r.headers['origin']&&!r.headers['origin'].includes('roblox'))return true;return false}
function getClientType(r){if(hasExecutorHeaders(r))return'executor';if(isBrowser(r))return'browser';if(isBot(r))return'bot';return'executor'}
async function logAccess(r,a,s,d={}){const log={ip:getIP(r),hwid:getHWID(r),ua:(r.headers['user-agent']||'').substring(0,80),action:a,success:s,path:r.path,client:getClientType(r),ts:new Date().toISOString(),...d};await db.addLog(log);return log}
function genChallenge(){const types=['math','bitwise','sequence','sum'];const type=types[Math.floor(Math.random()*types.length)];switch(type){case'math':const op=['+','-','*'][Math.floor(Math.random()*3)];const a=Math.floor(Math.random()*50)+10,b=Math.floor(Math.random()*20)+5,c=Math.floor(Math.random()*10)+1;let ans;if(op==='+')ans=(a+b)*c;else if(op==='-')ans=(a-b)*c;else ans=(a*b)+c;return{type:'math',puzzle:{a,b,c,op},answer:ans};case'bitwise':const x=Math.floor(Math.random()*200)+50,y=Math.floor(Math.random()*100)+20;const bop=['xor','and','or'][Math.floor(Math.random()*3)];let bans;if(bop==='xor')bans=x^y;else if(bop==='and')bans=x&y;else bans=x|y;return{type:'bitwise',puzzle:{x,y,op:bop},answer:bans};case'sequence':const start=Math.floor(Math.random()*15)+1,step=Math.floor(Math.random()*8)+2;return{type:'sequence',puzzle:{seq:[start,start+step,start+step*2,start+step*3]},answer:start+step*4};default:const nums=Array.from({length:5},()=>Math.floor(Math.random()*50)+1);return{type:'sum',puzzle:{numbers:nums},answer:nums.reduce((a,b)=>a+b,0)}}}
function isObfuscated(s){return s&&[/Luraph/i,/Moonsec/i,/IronBrew/i,/Prometheus/i,/PSU/i].some(r=>r.test(s.substring(0,500)))}
async function getScript(){const cached=await db.getCachedScript();if(cached)return cached;if(!config.SCRIPT_SOURCE_URL)return null;try{const res=await axios.get(config.SCRIPT_SOURCE_URL,{timeout:30000,headers:{'User-Agent':'Roblox/WinInet'},maxContentLength:50000000});if(typeof res.data==='string'&&res.data.length>50){await db.setCachedScript(res.data);return res.data}}catch(e){}return null}
function wrapScript(script,serverUrl){const o=config.OWNER_USER_IDS.join(','),w=config.WHITELIST_USER_IDS.join(','),b=`${serverUrl}/api/ban`,hb=`${serverUrl}/api/heartbeat`;return`local _O={${o}} local _W={${w}} local _B="${b}" local _HB="${hb}" local _P=game:GetService("Players") local _L=_P.LocalPlayer local _S=game:GetService("StarterGui") local _C=game:GetService("CoreGui") local _H=game:GetService("HttpService") local _TS=game:GetService("TeleportService") local _A=true local _SD=false local _CON={} local _THR={} local _RDY=false local _SID="${crypto.randomBytes(16).toString('hex')}"
local _IT={g={},m={}}
local _PG=nil
pcall(function() _PG=_L:FindFirstChild("PlayerGui") or _L:WaitForChild("PlayerGui",3) end)
local function _isW(u) if not _W or #_W==0 then return false end for _,i in ipairs(_W) do if u==i then return true end end return false end
local function _isO(u) if not _O or #_O==0 then return false end for _,i in ipairs(_O) do if u==i then return true end end return false end
local function _n(t,x,d) pcall(function() _S:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3}) end) end
local function _hw() local s,r=pcall(function() if gethwid then return gethwid() end return "FB_"..tostring(_L.UserId) end) return s and r or "UNK" end
local function _hp(u,d,m) local r=(syn and syn.request) or request or http_request or (http and http.request) if not r then return nil end m=m or"POST" local ok,res=pcall(function() return r({Url=u,Method=m,Headers={["Content-Type"]="application/json",["User-Agent"]="Roblox/WinInet",["x-hwid"]=_hw(),["x-roblox-id"]=tostring(_L.UserId),["x-place-id"]=tostring(game.PlaceId),["x-job-id"]=game.JobId,["x-session-id"]=_SID},Body=d and _H:JSONEncode(d) or nil}) end) if not ok then return nil end if res.StatusCode~=200 then return nil end local ps,pd=pcall(function() return _H:JSONDecode(res.Body) end) return ps and pd or nil end
local function _freeze() pcall(function() local sc=Instance.new("ScreenGui") sc.Name="X"..math.random(100000,999999) sc.IgnoreGuiInset=true sc.DisplayOrder=2147483647 sc.ResetOnSpawn=false sc.Parent=_C local fr=Instance.new("Frame") fr.Size=UDim2.new(1,0,1,0) fr.BackgroundColor3=Color3.new(0,0,0) fr.BorderSizePixel=0 fr.Parent=sc local tx=Instance.new("TextLabel") tx.Size=UDim2.new(1,0,1,0) tx.BackgroundTransparency=1 tx.Text="ACCESS DENIED" tx.TextColor3=Color3.new(1,0,0) tx.TextSize=48 tx.Font=Enum.Font.GothamBold tx.Parent=fr end) end
local function _fd(reason) _A=false _RDY=false _freeze() task.delay(0.5,function() pcall(function() _L:Kick(reason) end) task.wait(0.3) pcall(function() _TS:Teleport(9999999999) end) end) end
local function _ban(rs,t) if _SD then return end _SD=true _A=false _hp(_B,{hwid=_hw(),playerId=_L.UserId,playerName=_L.Name,reason=rs,toolsDetected=t or {},sessionId=_SID}) _n("⛔","Banned: "..rs,5) _fd(rs) end
local function _cl() if _SD then return end _SD=true _A=false _RDY=false for i=#_THR,1,-1 do pcall(task.cancel,_THR[i]) end for i=#_CON,1,-1 do pcall(function() _CON[i]:Disconnect() end) end end
_G._SCRIPT_CLEANUP=_cl
local _TP={"simplespy","httpspy","remotespy","hydroxide","infiniteyield","serverspy","scriptdumper","darkdex","dex_explorer"}
local _TM={"SimpleSpy","HttpSpy","RemoteSpy","Hydroxide","Dex","DexExplorer","InfiniteYield","IY_LOADED"}
local function _antiDebug() if not debug or not newcclosure then return end pcall(function() debug.getupvalue=newcclosure(function() return nil,nil end) debug.setupvalue=newcclosure(function() return nil end) debug.getlocal=newcclosure(function() return "x",nil end) end) end
local function _antiGC() if not getgc or not newcclosure then return end local _o=getgc local c=0 getgc=newcclosure(function(i) c=c+1 if c>20 then _ban("GC abuse",{}) return {} end local ok,r=pcall(_o,i) return ok and r or {} end) end
local function _doSnap() local e=getgenv and getgenv() or _G for _,m in ipairs(_TM) do if rawget(e,m) then _IT.m[m]=true end end if _C then pcall(function() for _,g in pairs(_C:GetChildren()) do if g:IsA("ScreenGui") then _IT.g[g.Name:lower()]=true end end end) end end
local function _snap() if _isW(_L.UserId) then _RDY=true return end _doSnap() task.wait(0.5) _doSnap() _RDY=true end
local function _det() if not _RDY or not _A or _isW(_L.UserId) then return false end local e=getgenv and getgenv() or _G for _,m in ipairs(_TM) do if rawget(e,m) and not _IT.m[m] then return true,"ENV",m end end if _C then for _,g in pairs(_C:GetChildren()) do if g:IsA("ScreenGui") then local nm=g.Name:lower() if not _IT.g[nm] then for _,p in ipairs(_TP) do if nm:find(p,1,true) then return true,"GUI",g.Name end end end end end end return false end
local function _mon() if _isW(_L.UserId) then return end table.insert(_THR,task.spawn(function() while not _RDY do task.wait(0.3) end task.wait(3) while _A and not _SD do task.wait(15) local d,c,s=_det() if d then _ban("Tool: "..(s or c),{c,s}) break end end end)) end
local function _watchGui() if _isW(_L.UserId) then return end if _C then table.insert(_CON,_C.ChildAdded:Connect(function(gui) if not _A or _SD or not _RDY or not gui:IsA("ScreenGui") then return end task.delay(1.5,function() if not _A or _SD then return end local nm=gui.Name:lower() if not _IT.g[nm] then for _,p in ipairs(_TP) do if nm:find(p,1,true) then _ban("Tool: "..gui.Name,{}) return end end end end) end)) end end
local function _heartbeat() table.insert(_THR,task.spawn(function() task.wait(10) while _A and not _SD do task.wait(25) local res=_hp(_HB,{sessionId=_SID,hwid=_hw()}) if res and res.action=="TERMINATE" then _ban("Session terminated",{}) break end end end)) end
local function _ownerOk() if not _O or #_O==0 then return true end for _,p in pairs(_P:GetPlayers()) do if _isO(p.UserId) and p~=_L then return false end end return true end
local function _ownerMon() if not _O or #_O==0 then return end table.insert(_THR,task.spawn(function() while _A and not _SD do task.wait(20) if not _ownerOk() then _n("⚠️","Owner detected",3) _cl() return end end end)) table.insert(_CON,_P.PlayerAdded:Connect(function(p) task.wait(1) if _isO(p.UserId) then _n("⚠️","Owner joined",3) _cl() end end)) end
if not _ownerOk() then _n("⚠️","Owner in server",3) return end
task.spawn(function() _antiDebug() _antiGC() _snap() _mon() _watchGui() _ownerMon() _heartbeat() end)
${script}`}
function getLoader(serverUrl){return`local S="${serverUrl}" local H=game:GetService("HttpService") local P=game:GetService("Players") local G=game:GetService("StarterGui") local L=P.LocalPlayer
local function n(t,x,d) pcall(function() G:SetCore("SendNotification",{Title=t,Text=x,Duration=d or 3}) end) end
local function hw() local s,r=pcall(function() if gethwid then return gethwid() end return "FB_"..tostring(L.UserId) end) return s and r or "UNK" end
local function hp(u,d) local r=(syn and syn.request) or request or http_request or (http and http.request) if not r then n("❌","No HTTP",5) return nil end local s,res=pcall(function() return r({Url=u,Method="POST",Headers={["Content-Type"]="application/json",["User-Agent"]="Roblox/WinInet",["x-hwid"]=hw(),["x-roblox-id"]=tostring(L.UserId),["x-place-id"]=tostring(game.PlaceId),["x-job-id"]=game.JobId},Body=H:JSONEncode(d)}) end) if not s then n("❌","Request failed",5) return nil end if res.StatusCode~=200 then local e pcall(function() e=H:JSONDecode(res.Body) end) if e and e.error then n("❌",e.error,5) end return nil end local ps,pd=pcall(function() return H:JSONDecode(res.Body) end) return ps and pd or nil end
local function xd(d,k) local r={} for i=1,#d do r[i]=string.char(bit32.bxor(d[i],string.byte(k,((i-1)%#k)+1))) end return table.concat(r) end
local function solve(p) if p.type=="math" then local a,b,c,op=p.puzzle.a,p.puzzle.b,p.puzzle.c,p.puzzle.op if op=="+" then return(a+b)*c elseif op=="-" then return(a-b)*c elseif op=="*" then return(a*b)+c end elseif p.type=="bitwise" then local x,y,op=p.puzzle.x,p.puzzle.y,p.puzzle.op if op=="xor" then return bit32.bxor(x,y) elseif op=="and" then return bit32.band(x,y) elseif op=="or" then return bit32.bor(x,y) end elseif p.type=="sequence" then local s=p.puzzle.seq return s[4]+(s[2]-s[1]) elseif p.numbers then local sum=0 for _,x in ipairs(p.numbers) do sum=sum+x end return sum end return 0 end
local function m() n("🔄","Connecting...",2) local c=hp(S.."/api/auth/challenge",{userId=L.UserId,hwid=hw(),placeId=game.PlaceId}) if not c then return end if not c.success then n("❌",c.error or "Failed",5) if c.error and tostring(c.error):find("Banned") then task.wait(1) L:Kick("Banned") end return end n("🔄","Verifying...",2) local v=hp(S.."/api/auth/verify",{challengeId=c.challengeId,solution=solve(c),timestamp=os.time()}) if not v or not v.success then n("❌",v and v.error or "Failed",5) return end n("✅","Success!",2) local fs if v.mode=="raw" then fs=v.script else local p={} for i,ch in ipairs(v.chunks) do p[i]=xd(ch,v.key) end fs=table.concat(p) end local fn=loadstring(fs) if fn then fs=nil v=nil c=nil pcall(fn) else n("❌","Load failed",5) end end
pcall(m)`}
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false,crossOriginResourcePolicy:false}));
app.use(cors({origin:'*',methods:['GET','POST','DELETE','OPTIONS'],allowedHeaders:['Content-Type','x-admin-key','x-hwid','x-roblox-id','x-place-id','x-job-id','x-session-id']}));
app.use(express.json({limit:'10mb'}));
app.set('trust proxy',1);
app.use(rateLimit({windowMs:60000,max:100,keyGenerator:r=>getIP(r)}));
app.use(async(req,res,next)=>{const ban=await db.isBanned(null,getIP(req),null);if(ban.blocked){const ct=getClientType(req);if(ct==='browser')return res.status(403).type('html').send(TRAP_HTML);return res.status(403).json({error:'Blocked'})}next()});
app.get('/',(r,res)=>{const ct=getClientType(r);if(ct==='browser')return res.status(403).type('html').send(TRAP_HTML);if(ct==='bot')return res.type('text/plain').send(genFakeScript());res.json({status:'ok',version:'6.3.0'})});
app.get('/health',(r,res)=>res.json({status:'ok'}));
app.get(['/loader','/api/loader.lua','/api/loader','/l'],async(r,res)=>{const ct=getClientType(r);await logAccess(r,'LOADER_'+ct.toUpperCase(),ct==='executor');if(ct==='browser')return res.status(403).type('html').send(TRAP_HTML);if(ct==='bot')return res.type('text/plain').send(genFakeScript());const url=process.env.RENDER_EXTERNAL_URL||`${r.protocol}://${r.get('host')}`;res.type('text/plain').send(getLoader(url))});
app.post('/api/auth/challenge',async(r,res)=>{const ct=getClientType(r);await logAccess(r,'CHALLENGE_'+ct.toUpperCase(),ct==='executor');if(ct==='browser')return res.status(403).json({success:false,error:'Browser not allowed'});if(ct==='bot')return res.status(403).json({success:false,error:'Invalid client'});const{userId,hwid,placeId}=r.body;if(!userId||!hwid||!placeId)return res.status(400).json({success:false,error:'Missing fields'});const uid=parseInt(userId),pid=parseInt(placeId);if(isNaN(uid)||isNaN(pid))return res.status(400).json({success:false,error:'Invalid format'});const ip=getIP(r);const ban=await db.isBanned(hwid,ip,uid);if(ban.blocked)return res.status(403).json({success:false,error:'Banned: '+ban.reason});if(config.ALLOWED_PLACE_IDS&&config.ALLOWED_PLACE_IDS.length>0&&!config.ALLOWED_PLACE_IDS.includes(pid))return res.status(403).json({success:false,error:'Game not allowed'});const id=crypto.randomBytes(16).toString('hex');const chal=genChallenge();await db.setChallenge(id,{id,userId:uid,hwid,placeId:pid,ip,...chal},60);res.json({success:true,challengeId:id,type:chal.type,puzzle:chal.puzzle,expiresIn:60})});
app.post('/api/auth/verify',async(r,res)=>{const ct=getClientType(r);await logAccess(r,'VERIFY_'+ct.toUpperCase(),ct==='executor');if(ct==='browser')return res.status(403).json({success:false,error:'Browser not allowed'});if(ct==='bot')return res.status(403).json({success:false,error:'Invalid client'});const{challengeId,solution,timestamp}=r.body;if(!challengeId||solution===undefined||!timestamp)return res.status(400).json({success:false,error:'Missing fields'});const challenge=await db.getChallenge(challengeId);if(!challenge)return res.status(403).json({success:false,error:'Challenge expired'});if(challenge.ip!==getIP(r))return res.status(403).json({success:false,error:'IP mismatch'});if(parseInt(solution)!==challenge.answer)return res.status(403).json({success:false,error:'Wrong solution'});await db.deleteChallenge(challengeId);const script=await getScript();if(!script)return res.status(500).json({success:false,error:'Script not configured'});const url=process.env.RENDER_EXTERNAL_URL||`${r.protocol}://${r.get('host')}`;const wrapped=wrapScript(script,url);const isObf=config.SCRIPT_ALREADY_OBFUSCATED||isObfuscated(script);const sessionId=crypto.randomBytes(16).toString('hex');SESSIONS.set(sessionId,{hwid:challenge.hwid,ip:challenge.ip,userId:challenge.userId,created:Date.now()});if(isObf){return res.json({success:true,mode:'raw',script:wrapped,sessionId,ownerIds:config.OWNER_USER_IDS||[],whitelistIds:config.WHITELIST_USER_IDS||[]})}const key=genSessionKey(challenge.userId,challenge.hwid,timestamp,config.SECRET_KEY);const chunks=[];for(let i=0;i<wrapped.length;i+=1500){const chunk=wrapped.substring(i,i+1500);const enc=[];for(let j=0;j<chunk.length;j++)enc.push(chunk.charCodeAt(j)^key.charCodeAt(j%key.length));chunks.push(enc)}res.json({success:true,mode:'encrypted',key,chunks,sessionId,ownerIds:config.OWNER_USER_IDS||[],whitelistIds:config.WHITELIST_USER_IDS||[]})});
app.post('/api/heartbeat',async(r,res)=>{const{sessionId,hwid}=r.body;if(!sessionId||!hwid)return res.json({action:'TERMINATE'});const session=SESSIONS.get(sessionId);if(!session||session.hwid!==hwid)return res.json({action:'TERMINATE'});const ban=await db.isBanned(hwid,getIP(r),session.userId);if(ban.blocked)return res.json({action:'TERMINATE'});session.lastSeen=Date.now();res.json({success:true,action:'CONTINUE'})});
app.post('/api/ban',async(r,res)=>{const{hwid,playerId,reason,toolsDetected,sessionId}=r.body;if(!hwid&&!playerId)return res.status(400).json({error:'Missing id'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();if(hwid)await db.addBan(hwid,{hwid,ip:getIP(r),playerId,reason:reason||'Auto',toolsDetected,banId,ts:new Date().toISOString()});if(playerId)await db.addBan(String(playerId),{playerId,reason:reason||'Auto',banId,ts:new Date().toISOString()});if(sessionId)SESSIONS.delete(sessionId);res.json({success:true,banId})});
app.get('/api/admin/stats',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Unauthorized'});res.json({success:true,stats:await db.getStats(),sessions:SESSIONS.size})});
app.get('/api/admin/logs',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Unauthorized'});res.json({success:true,logs:await db.getLogs(Math.min(parseInt(r.query.limit)||50,500))})});
app.get('/api/admin/bans',async(r,res)=>{const key=r.headers['x-admin-key']||r.query.key;if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Unauthorized'});res.json({success:true,bans:await db.getAllBans()})});
app.delete('/api/admin/bans/:id',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Unauthorized'});const bans=await db.getAllBans();const f=bans.find(b=>b.banId===r.params.id);if(f){await db.removeBan(f.key);return res.json({success:true})}res.status(404).json({error:'Not found'})});
app.post('/api/admin/bans',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Unauthorized'});const{hwid,ip,playerId,reason}=r.body;if(!hwid&&!ip&&!playerId)return res.status(400).json({error:'Required'});const banId=crypto.randomBytes(8).toString('hex').toUpperCase();if(hwid)await db.addBan(hwid,{hwid,reason:reason||'Manual',banId,ts:new Date().toISOString()});if(playerId)await db.addBan(String(playerId),{playerId,reason:reason||'Manual',banId,ts:new Date().toISOString()});if(ip)await db.addBan(ip,{ip,reason:reason||'Manual',banId,ts:new Date().toISOString()});res.json({success:true,banId})});
app.post('/api/admin/cache/clear',async(r,res)=>{const key=r.headers['x-admin-key'];if(!key||!secureCompare(key,config.ADMIN_KEY))return res.status(403).json({error:'Unauthorized'});await db.setCachedScript(null);res.json({success:true})});
app.use('*',(r,res)=>{const ct=getClientType(r);if(ct==='browser')return res.status(404).type('html').send(TRAP_HTML);if(ct==='bot')return res.type('text/plain').send(genFakeScript());res.status(404).json({error:'Not found'})});
setInterval(()=>{const now=Date.now();for(const[k,v]of SESSIONS)if(now-v.created>3600000)SESSIONS.delete(k)},60000);
app.listen(process.env.PORT||3000,'0.0.0.0');
